package-lock.json
package.json
packages/schema/src/schema.ts

feat(types): improve JsonType

---

packages/http/src/__tests__/router.test.ts
packages/http/src/__tests__/static/foo.js
packages/http/src/router.ts

fix #9 
I can't pass the test bucause of the type error.

fix(http): router.serve process bug

---

.eslintrc
.prettierrc
packages/cors/src/__tests__/error-response.ts
packages/cors/src/__tests__/example-app.ts
packages/cors/src/index.ts
packages/example/src/pages/components/Form.tsx
packages/example/src/pages/todos/index.tsx
packages/example/src/temp.ts
packages/graphql/src/build.ts
packages/graphql/src/weather.schema.ts
packages/http/src/__tests__/http.test.ts
packages/http/src/__tests__/router.test.ts
packages/http/src/basenames.ts
packages/http/src/http.ts
packages/http/src/requestInfo.ts
packages/http/src/responseInfo.ts
packages/http/src/router.ts
packages/http/src/types.ts
packages/http/src/util.ts
packages/pipeline/src/__tests__/compose.test.js
packages/pipeline/src/__tests__/pipeline.test.ts
packages/pipeline/src/context.ts
packages/pipeline/src/pipeline.ts
packages/react/src/react.tsx
packages/schema/src/__tests__/schema.test.ts
packages/schema/src/schema.ts
packages/schema/src/transformer.ts
packages/schema/src/types.ts
packages/schema/src/validator.ts

update eslint config

---

packages/farrow-http/README.md

doc(http): support https

---

packages/farrow-http/fixtures/bar.js
packages/farrow-http/fixtures/static/foo.js
packages/farrow-http/src/__tests__/http.test.ts
packages/farrow-http/src/router.ts

fix(http): serve prevent directory traversal attack

---

package-lock.json
packages/farrow-vite/src/__tests__/index.html
packages/farrow-vite/src/__tests__/sub/index.html
packages/farrow-vite/src/__tests__/vite.test.ts
packages/farrow-vite/src/vite.ts

1.Avoid 404 when refresh a SPA sub page.  
2. Unit test provided.

feat(farrow-vite): use default html if target html not find

---

package.json

feat(package.json): add `npm run format` to prerelease stage

---

packages/farrow-api-client/package.json
packages/farrow-api-client/src/apiPipeline.ts
packages/farrow-api/src/__tests__/expected/01.ts
packages/farrow-api/src/codegen.ts

- api: codegen add `type: Single`
- api-client: dataloader setImmediate error

fix some error

---

packages/farrow/__tests__/farrow-api.test.ts
packages/farrow/package.json
packages/farrow/src/api-client/index.ts
packages/farrow/src/api-client/replaceUrl.ts
packages/farrow/src/build.ts

support #64  
1. Rewrite the src url  when build time
2. Unit test provided.

feat(farrow): add feature:  replace src url in generated client code when farrow build

---

packages/farrow/src/api-client/replaceUrl.ts

fix(farrow): lose `export const url =` after replace

---

packages/farrow-next/package.json

https://nextjs.org/docs/upgrading#upgrading-from-version-10-to-11

Fix Next.js 11 compatibility

---

package-lock.json
packages/farrow-express/README.md
packages/farrow-express/fixtures/bar.js
packages/farrow-express/fixtures/static/foo.js
packages/farrow-express/package.json
packages/farrow-express/src/__tests__/express.test.ts
packages/farrow-express/src/adapter.ts
packages/farrow-express/src/context.ts
packages/farrow-express/src/index.ts
packages/farrow-express/tsconfig.json
tsconfig.dist.json

Just for express.
Solution for Koa has some problem to resolve.

feat(farrow-express): add

---

package-lock.json
packages/farrow-express/README.md
packages/farrow-koa/README.md
packages/farrow-koa/fixtures/bar.js
packages/farrow-koa/fixtures/static/foo.js
packages/farrow-koa/package.json
packages/farrow-koa/src/__tests__/koa.test.ts
packages/farrow-koa/src/adapter.ts
packages/farrow-koa/src/context.ts
packages/farrow-koa/src/index.ts
packages/farrow-koa/tsconfig.json
tsconfig.dist.json

* feat(farrow-koa): add
* doc(farrow-koa): readme
* doc(farrow-express): readme

feat(farrow-koa): add

---

tsconfig.dist.json
tsconfig.esm.json

chore(farrow-json-schema): build

---

package-lock.json
packages/farrow-json-schema/tsconfig.esm.json

my mistake again. :dizzy_face:

fix(farrow-json-schema): esm build

---

packages/farrow-api-client/README.md
packages/farrow-api-client/src/apiPipeline.ts

feat(farrow-api-client): custom fetcher

---

packages/farrow-pipeline/src/__tests__/pipeline.test.ts
packages/farrow-pipeline/src/pipeline.ts

feat(farrow-pipeline): run onLast with context optionally

---

.changeset/real-kiwis-pump.md
package.json
packages/farrow-http/__tests__/router.test.ts
packages/farrow-http/src/basenames.ts

Fix http route match

---

packages/create-farrow-app/package.json

https://github.com/farrow-js/farrow-docs/issues/10
https://classic.yarnpkg.com/en/docs/cli/create
https://github.com/facebook/create-react-app/blob/c7627ce96c4674f327081f101dd0e2771be4d045/packages/create-react-app/package.json#L26

fix(create-farrow-app): script name: farrow -> create-farrow-app

---

.changeset/poor-spiders-admire.md
packages/farrow-http/__tests__/basename.test.ts
packages/farrow-http/__tests__/router.test.ts
packages/farrow-http/src/basenames.ts

docs(changeset): Fix http route match basename bug

---

.changeset/rich-paws-tie.md
packages/farrow-api-client/src/apiPipeline.ts

feat(farrow-api-client): api.setFetcher && api.invoke with fetcher

---

.changeset/lucky-walls-beg.md
packages/farrow/src/index.ts

feat(farrow): defineConfig

---

.changeset/four-pants-admire.md
README.md
examples/todo-app/package.json
packages/create-farrow-app/templates/farrow-vite-react/package.json
packages/farrow-http/__tests__/https.test.ts
packages/farrow-http/src/https.ts
packages/farrow-vite/CHANGELOG.md
pnpm-lock.yaml

fix(farrow-http): tsl -> tls

---

.changeset/pink-hounds-allow.md
examples/benchmark/farrow.config.js
examples/benchmark/farrow.sample.config.js
examples/benchmark/farrow.schema.config.js
examples/benchmark/index.js
examples/benchmark/src/schema/index.ts
packages/farrow/bin/scripts.js
packages/farrow/fixtures/project0/package.json
packages/farrow/package.json
packages/farrow/scripts/build.js
packages/farrow/scripts/dev.js
packages/farrow/scripts/start.js
packages/farrow/src/bin/index.ts
packages/farrow/src/scripts/build.ts
packages/farrow/src/scripts/dev.ts
packages/farrow/src/scripts/start.ts
pnpm-lock.yaml
pnpm-workspace.yaml

refactor: farrow cli woth commander

---

.changeset/fresh-spiders-fail.md
packages/farrow-http/src/router.ts
packages/farrow-vite/src/vite.ts

Fix farrow vite use lazy, http need async pipeline

---

.changeset/slow-roses-pull.md
packages/farrow-api-server/__tests__/apiService.test.ts
packages/farrow-api-server/src/apiService.ts
pnpm-lock.yaml

feat(api-server): optional introspection

---

examples/benchmark/package.json
examples/example/package.json
examples/next-app/package.json
examples/todo-app/package.json
packages/create-farrow-app/package.json
packages/create-farrow-app/templates/farrow-next-react/package.json
packages/create-farrow-app/templates/farrow-only/package.json
packages/create-farrow-app/templates/farrow-vite-react/package.json
packages/farrow-api-client/package.json
packages/farrow-api-server/package.json
packages/farrow-api/package.json
packages/farrow-cors/package.json
packages/farrow-deno-api/package.json
packages/farrow-express/package.json
packages/farrow-federation/__tests__/__snapshots__/federation.test.ts.snap
packages/farrow-federation/__tests__/federation.test.ts
packages/farrow-federation/package.json
packages/farrow-http/package.json
packages/farrow-json-schema/package.json
packages/farrow-koa/package.json
packages/farrow-module/package.json
packages/farrow-next-server/package.json
packages/farrow-next/package.json
packages/farrow-pipeline/package.json
packages/farrow-react/package.json
packages/farrow-schema/package.json
packages/farrow-vite/package.json
packages/farrow/__tests__/farrow-server.test.ts
packages/farrow/package.json
pnpm-lock.yaml

- jest timeout 10000 -> 50000
- update jest to v29

fix: testcase
